### ISSUE TITLE
Falha nos webhooks do github

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#268]
O endpoint de recebimento do webhook do github está com o seguinte problema:

```
<!doctype html>
<html class="theme-light">
<!--
ErrorException: Trying to access array offset on value of type null in file /home/practiceqamural/qa.mural.practice.uffs.cc/app/Http/Controllers/API/GithubWebhookController.php on line 24

#0 /home/practiceqamural/qa.mural.practice.uffs.cc/app/Http/Controllers/API/GithubWebhookController.php(24): Illuminate\Foundation\Bootstrap\HandleExceptions-&gt;handleError(8, 'Trying to acces...', '/home/practiceq...', 24, Array)
#1 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\API\GithubWebhookController-&gt;issueComment(Object(Illuminate\Http\Request))
#2 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller-&gt;callAction('issueComment', Array)
#3 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\Routing\ControllerDispatcher-&gt;dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\API\GithubWebhookController), 'issueComment')
#4 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\Routing\Route-&gt;runController()
#5 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\Routing\Route-&gt;run()
#6 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#7 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#9 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handle(Object(Illuminate\Http\Request), Object(Closure), 180, '1')
#11 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#13 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router-&gt;runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router-&gt;runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#15 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Illuminate\Http\Request))
#16 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router-&gt;dispatch(Object(Illuminate\Http\Request))
#17 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#18 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#32 /home/practiceqamural/qa.mural.practice.uffs.cc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter(Object(Illuminate\Http\Request))
#33 /home/practiceqamural/qa.mural.practice.uffs.cc/public/index.php(55): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
#34 {main}
```

**Comment by oraphaBorges** [comment]
@Dovyski poderia dar uma descrição maior da situação em que ocorreu o erro? pois nos testes em ambiente de desenvolvimento a integração com o github tem funcionado perfeitamente.

**Comment by CleissonVieira** [comment]
PR que resolve a situação ainda não feito aceito.
